---
kind: pipeline
name: pr

steps:
- name: npm install
  image: node
  commands:
  - npm ci -d

- name: commitlint
  image: node
  commands:
  - npx commitlint --from master --to HEAD || exit 1

- name: npm test
  image: node
  commands:
  - npm test

trigger:
  event:
  - pull_request

---
kind: pipeline
name: release

steps:
- name: npm install
  image: node
  commands:
  - npm ci -d

- name: semantic-release
  image: node
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  commands:
    - npx semantic-release

trigger:
  branch:
  - master
  event:
  - push
